# Dockerfile

# Use Python 3.9 as the base image
FROM python:3.9-slim

# working directory
WORKDIR /app

# Copy the Python script into the container
COPY insert_data.py .

# Install pymysql
RUN pip install pymysql

# Command to run the Python script
CMD ["python", "insert_data.py"]